language: python
python:
  - 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

install:
  - pip install -r requirements.txt

script:
  - set -e
  # Generate an example intake-bluesky pacakge by simulating user input to cookiecutter.
  - ./run_cookiecutter_example.py
  # Install the new package.
  - pip install -e ./intake-bluesky-example 
  # Check that it is importable.
  - python -c "import intake_bluesky.example"
  # Now install intake-bluesky-example's development dependencies.
  - pip install -r intake-bluesky-example/requirements-dev.txt 
  # Run the example parametrized test.
  - pytest intake-bluesky-example/
  # Run flake8.
  - flake8 --max-line-length=115 intake-bluesky-example/
